title: Cone's Dev Blog
author: ConeDome
email: elijycombs@students.k12k.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is where I'll write about the AMAZING things i do with coding and about how awesome I am at it.
# social links
twitter_username: itsconedome # DO NOT include the @ character, or else the build will fail!
github_username:  ConeDome # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
